# Generated by Django 4.2.11 on 2026-03-19 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("digests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("suggest_themes", "Suggestion de themes"),
                            ("suggest_sources", "Suggestion de sources"),
                            ("rank_articles", "Ranking d'articles"),
                            ("generate_posts", "Generation de posts"),
                            ("other", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "model",
                    models.CharField(default="llama-3.3-70b-versatile", max_length=100),
                ),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="digests_aiu_created_1dd985_idx"
                    ),
                    models.Index(
                        fields=["feature", "-created_at"],
                        name="digests_aiu_feature_83dc23_idx",
                    ),
                ],
            },
        ),
    ]
