# Generated by Django 4.2.11 on 2026-03-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digests", "0002_aiusagelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En cours"),
                            ("completed", "Termine"),
                            ("failed", "Echoue"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("current_step", models.CharField(default="init", max_length=50)),
                (
                    "current_step_label",
                    models.CharField(default="Initialisation...", max_length=200),
                ),
                ("total_sources", models.IntegerField(default=0)),
                ("scraped_sources", models.IntegerField(default=0)),
                ("total_articles_found", models.IntegerField(default=0)),
                ("total_articles_new", models.IntegerField(default=0)),
                ("total_themes", models.IntegerField(default=0)),
                ("processed_themes", models.IntegerField(default=0)),
                ("total_digests_created", models.IntegerField(default=0)),
                ("steps_log", models.JSONField(default=list)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
