# Generated by Django 4.2.28 on 2026-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digests", "0003_pipelinerun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
