# Generated by Django 4.2.11 on 2026-03-15 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nom du site/source", max_length=255),
                ),
                ("url", models.URLField(unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS Feed"),
                            ("html", "HTML Scraping"),
                            ("api", "API"),
                        ],
                        default="rss",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                (
                    "success_count",
                    models.IntegerField(
                        default=0, help_text="Nombre de scrapes réussis"
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, help_text="Nombre d'erreurs"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom du thème (ex: 'Crypto & Web3')", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description optionnelle pour mémo"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        help_text="Liste de mots-clés pour filtrer les articles",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Quotidien"), ("weekly", "Hebdomadaire")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "articles_last_digest",
                    models.IntegerField(
                        default=0, help_text="Nombre d'articles du dernier digest"
                    ),
                ),
                ("last_digest_sent", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="themes", to="themes.source"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "ordering": ["-is_active", "-updated_at"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
