# Generated by Django 4.2.11 on 2026-03-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="filter_criteria",
            field=models.JSONField(
                default=list,
                help_text="Criteres de pertinence definis par l'utilisateur (liste de strings)",
            ),
        ),
    ]
