# Generated by Django 4.2.11 on 2026-03-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0002_theme_filter_criteria"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuratedSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS Feed"),
                            ("html", "HTML Scraping"),
                            ("api", "API"),
                        ],
                        default="rss",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description courte de la source"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="Tags/categories pour le matching (ex: ['tech', 'startup', 'fintech'])",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Plus haut = propose en premier"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Source curatee",
                "verbose_name_plural": "Sources curatees",
                "ordering": ["-priority", "name"],
            },
        ),
    ]
