# Generated by Django 4.2.28 on 2026-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0003_curatedsource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curatedsource",
            name="url",
            field=models.URLField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="logo_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
