# Generated by Django 4.2.28 on 2026-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(help_text="Jour dans la campagne (1-90)")),
                ("date_label", models.CharField(max_length=100)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter/X"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("informatif", "Informatif"),
                            ("preuve_sociale", "Preuve sociale"),
                            ("promotionnel", "Promotionnel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("hashtags", models.JSONField(default=list)),
                ("image_description", models.TextField(blank=True)),
                ("cta", models.CharField(blank=True, max_length=500)),
                ("objective", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("valide", "Valide"),
                            ("publie", "Publie"),
                            ("rejete", "Rejete"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="social_posts/"),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.IntegerField(default=1)),
            ],
            options={
                "ordering": ["day", "platform"],
            },
        ),
    ]
