# Generated by Django 4.2.28 on 2026-03-16 18:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_seed_month1_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
