# Generated by Django 4.2.28 on 2026-03-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_theme_change",
            field=models.DateTimeField(
                blank=True,
                help_text="Derniere modification de theme (limite 1x/semaine)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Numero WhatsApp au format +33...",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_enabled",
            field=models.BooleanField(
                default=False, help_text="Activer les digests par WhatsApp"
            ),
        ),
    ]
